### ISSUE TITLE
panic while requesting a non existing dimension

### ISSUE THREAD

**Issue by loeffert** [foomo/contentserver#3]
at least in version 1.2.0 requesting a non existing dimension panics like:

```
goroutine 8 [running]:
panic(0x7493a0, 0xc820014060)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/foomo/contentserver/server/repo.(*Repo).GetURI(0xc820070f90, 0xc820014b40, 0x2, 0xc8207a3950, 0x24, 0x0, 0x0)
    /go/src/github.com/foomo/contentserver/server/repo/repo.go:106 +0x82
github.com/foomo/contentserver/server/repo.(*Repo).GetURIs(0xc820070f90, 0xc820014b40, 0x2, 0xc8207f9280, 0x2, 0x4, 0x62)
    /go/src/github.com/foomo/contentserver/server/repo/repo.go:86 +0x110
github.com/foomo/contentserver/server.handleSocketRequest(0xc820014a20, 0x7, 0xc82045e230, 0x68, 0x68, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/foomo/contentserver/server/socket.go:36 +0x145c
github.com/foomo/contentserver/server.handleConnection(0x7fe77e3886d8, 0xc820076020)
    /go/src/github.com/foomo/contentserver/server/socket.go:116 +0x794
created by github.com/foomo/contentserver/server.RunSocketServer
    /go/src/github.com/foomo/contentserver/server/socket.go:166 +0x4e4
tcp 0.0.0.0:80 http://contentserver:contentserver@site/contentserver/export
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ddce2]
```

looks like the php socket connection is then waiting for a timeout in Foomo.ContentServer

**Comment by franklinkim** [comment]
♻️ Stale
